const tree = [
  {
    _id: '1',
    name: 'Guava',
    meaning: 'Life',
    image:
      'https://ik.imagekit.io/cz92t2phsuf/Cultivist/Untitled_design__12__6gv-o1vDf.png?updatedAt=1634726523579',
    contribution: 250,
    countInStock: 10,
    CO2: 50,
    shortDescription: 'Plant a Guava Tree',
    description: 'Guava Tree',
    nameOnTree: '',
    occasion: '',
    occasionText: '',
  },
  {
    _id: '2',
    name: 'Neem',
    meaning: 'Energy',
    image:
      'https://ik.imagekit.io/cz92t2phsuf/Cultivist/Untitled_design__13__1bfylOcAgQu.png?updatedAt=1634726995472',
    contribution: 250,
    countInStock: 10,
    CO2: 60,
    shortDescription: 'Plant a Neem Tree',
    description: '',
    nameOnTree: '',
    occasion: '',
    occasionText: '',
  },
  {
    _id: '3',
    name: 'Green Apple',
    meaning: 'Relief',
    image:
      'https://ik.imagekit.io/cz92t2phsuf/Cultivist/Untitled_design__16__iiSxMUoY1.png?updatedAt=1634726917563',
    contribution: 250,
    countInStock: 10,
    CO2: 70,
    shortDescription: 'Plant a Green Apple Tree',
    description: '',
    nameOnTree: '',
    occasion: '',
    occasionText: '',
  },
  {
    _id: '4',
    name: 'Mango',
    meaning: 'Sweetness',
    image:
      'https://ik.imagekit.io/cz92t2phsuf/Cultivist/Untitled_design__15__4Clsw84QRrm.png?updatedAt=1634726918240',
    contribution: 300,
    countInStock: 10,
    CO2: 80,
    shortDescription: 'Plant a Mango Tree',
    description: '',
    nameOnTree: '',
    occasion: '',
    occasionText: '',
  },
  {
    _id: '5',
    name: 'Peach',
    meaning: 'Resilence',
    image:
      'https://ik.imagekit.io/cz92t2phsuf/Cultivist/Untitled_design__17__LE_Jkwbrj.png?updatedAt=1634727085673',
    contribution: 250,
    countInStock: 10,
    CO2: 90,
    shortDescription: 'Plant a Peach Tree',
    description: '',
    nameOnTree: '',
    occasion: '',
    occasionText: '',
  },
];

export default tree;
